### ISSUE TITLE
how to trigger mlflow project code which is not in master branch?

### ISSUE THREAD

**Issue by j-arpit** [mlflow/mlflow-example#16]
When we use mlflow run git://url it is triggering the code from master branch only. Is there any way to trigger the code which is not in master branch?

**Comment by srivastavakushagra999** [comment]
Same question as above

**Comment by j-arpit** [comment]
Mlflow project only supports triggers from Head/Default Branch.
mlflow/mlflow/projects/utils.py line No: 234
` g = git.cmd.Git(dst_dir)
        cmd = ["git", "remote", "show", "origin"]
        output = g.execute(cmd)
        head_branch = _get_head_branch(output)`
